const URL_BIS_ROOT = "http://msk-rss-appb2:8443/rss/ocsdb/";
const PATH_OCSDB_POINT = "ocsdb/"
const URL_RSSMB_ROOT = "http://msk-rss-appb2:8765/rssrep/rss/rssmb/";
const PATH_RSSMB_POINT = "rssmb/"
// const URL_RSSMB_ROOT = "http://msk-rss-appa1:8444/rss/rssmb/";
const URL_RSSMB_ROAM_OPERATOR = "http://msk-rss-appb2:8765/rssrep/rssmb/operator/";
const PATH_RSSMB_ROAM_OPERATOR = "rssmb/operator/";
// const URL_RSSMB_ROAM_OPERATOR="http://msk-rss-appa1:8444/rssmb/operator/";
const BIS_TESD_DATA_POINT = "get-testData";
const UPLOAD_PRICE = "priceup";
const UPLOAD_REPRICE = "repricing/repriceup";
const CHECK_PRICE_LIST_MAP = "checkPriceMapping";
const CHANGE_RTPL = "setRatePlans";
const VIEW_RTPL = "rtpldata";
const CDR_TEST = "cdrtst";
const LOAD_RMOP = "loadrmop";
const CDR_DATA = "calls";
const PSET_DIR_PARAM = "psdirparam";
const CALL_ERROR = "callerr";
const CALL_ERR_PROC = "callerrproc";
const CALL_ERR_CHECK = "callerrcheck";
const GET_RTPL_ID = "getrtplid";
const SET_HRS_RTPL_ID = "sethrsrtpl";
const GET_RAP = "getrap";
const GET_MSG_RAP_LIST = "getmsgrap";
const CALL_RAP_REPROC = "rapreproc";
const ADD_TEST_RMOP = "addTestRmop";
const SET_S4H = "sets4h";
const ROAM_OPEN = "roamopen";
const GET_COUNTRIES = "countries";
const GET_ROAM_OPERATORS = "roamoperators";
const GET_CURRENCIES = "currencies";
const ADD_EXCH = "addexch";
const UPLOAD_DEF = "updef";
const GET_DEF = "getdef";
const UPLOAD_LAC = "uplac";
const DEFRU = "setdef";
const ADD_LAC_REG = "addlacreg";
const GET_REGIONS="regions";
const GET_RTPL_LIST="getListRatePlans";
const OCSDB_ADD_RMOP="addRmop";
const READ_WRKDEF="readwrkdef";
const READ_REPRICE="repricing/readreprice";
const OCSDB_GET_RNDT="repricing/roundtypes";
const OCSDB_GET_REPRICING_RTPL="repricing/getRtplList";
const OCSDB_CHECK_REPRICING_PRICE="repricing/checkpricelist";
const OCSDB_CHANGE_REPRICING_PRICES="repricing/changePrices";
const OCSDB_ADD_NEW_REPRICING_RTPL="repricing/addnewrtpl";

export const URI_API_SERVER = "http://msk-rss-appb2:8765";
export const API_TEST_DATA = PATH_OCSDB_POINT + BIS_TESD_DATA_POINT;
export const API_UPLOAD_PRICE = PATH_OCSDB_POINT + UPLOAD_PRICE
export const API_UPLOAD_REPRICE = PATH_OCSDB_POINT + UPLOAD_REPRICE
export const API_READ_WRKDEF= PATH_OCSDB_POINT + READ_WRKDEF
export const API_READ_REPRICE= PATH_OCSDB_POINT + READ_REPRICE
export const API_CHECK_PRICE_LIST_MAP = PATH_OCSDB_POINT + CHECK_PRICE_LIST_MAP;
export const API_CHANGE_RTPL = PATH_OCSDB_POINT + CHANGE_RTPL;
export const API_VIEW_RTPL = PATH_OCSDB_POINT + VIEW_RTPL;
export const API_CDR_TEST = PATH_OCSDB_POINT + CDR_TEST;
export const API_PSET_DIR_PARAM = PATH_OCSDB_POINT + PSET_DIR_PARAM;
export const API_GET_RTPL_ID = PATH_OCSDB_POINT + GET_RTPL_ID;
export const API_UPLOAD_DEF = PATH_OCSDB_POINT + UPLOAD_DEF;
export const API_GET_DEF = PATH_OCSDB_POINT + GET_DEF;
export const API_DEFRU = PATH_OCSDB_POINT + DEFRU;
export const API_OCS_ADD_LAC_REG = PATH_OCSDB_POINT + ADD_LAC_REG;
export const API_GET_RTPL_LIST=PATH_OCSDB_POINT+GET_RTPL_LIST;
export const API_OCSDB_ADD_RMOP=PATH_OCSDB_POINT+OCSDB_ADD_RMOP;
export const API_GET_ROUND_TYPES=PATH_OCSDB_POINT+OCSDB_GET_RNDT
export const API_GET_REPRICING_RTPL=PATH_OCSDB_POINT+OCSDB_GET_REPRICING_RTPL
export const API_CHECK_REPRICING_PRICE=PATH_OCSDB_POINT+OCSDB_CHECK_REPRICING_PRICE
export const API_CHANGE_REPRICING_PRICES=PATH_OCSDB_POINT+OCSDB_CHANGE_REPRICING_PRICES
export const API_ADD_NEW_REPRICING_RTPL=PATH_OCSDB_POINT+OCSDB_ADD_NEW_REPRICING_RTPL

export const API_CALL_DATA = PATH_RSSMB_POINT + CDR_DATA;
export const API_LOAD_RMOP = PATH_RSSMB_POINT + LOAD_RMOP;
export const API_CALL_ERRORS = PATH_RSSMB_POINT + CALL_ERROR;
export const API_CALL_ERR_PROC = PATH_RSSMB_POINT + CALL_ERR_PROC;
export const API_CALL_ERR_CHECK = PATH_RSSMB_POINT + CALL_ERR_CHECK;
export const API_SET_HRS_RTPL_ID = PATH_RSSMB_POINT + SET_HRS_RTPL_ID;
export const API_GET_RAP = PATH_RSSMB_POINT + GET_RAP;
export const API_GET_MSG_RAP_LIST = PATH_RSSMB_POINT + GET_MSG_RAP_LIST;
export const API_RAP_REPROC = PATH_RSSMB_POINT + CALL_RAP_REPROC;

export const API_ADD_TEST_RMOP = PATH_RSSMB_ROAM_OPERATOR + ADD_TEST_RMOP;
export const API_SET_S4H = PATH_RSSMB_ROAM_OPERATOR + SET_S4H;
export const API_ROAM_OPEN = PATH_RSSMB_ROAM_OPERATOR + ROAM_OPEN;
export const API_GET_COUNTRIES = PATH_RSSMB_ROAM_OPERATOR + GET_COUNTRIES;
export const API_GET_ROAM_OPERATORS = PATH_RSSMB_ROAM_OPERATOR + GET_ROAM_OPERATORS;
export const API_GET_CURRENCIES = PATH_RSSMB_ROAM_OPERATOR + GET_CURRENCIES;
export const API_ADD_EXCH = PATH_RSSMB_ROAM_OPERATOR + ADD_EXCH;
export const API_ADD_LAC_REG = PATH_RSSMB_ROAM_OPERATOR + ADD_LAC_REG;
export const API_GET_REGIONS = PATH_RSSMB_ROAM_OPERATOR + GET_REGIONS;
export const API_UPLOAD_LAC = PATH_RSSMB_ROAM_OPERATOR + UPLOAD_LAC;

export const DEF_PARAM_START_DATE = 'Дата начала применения ТП';
export const DEF_PARAM_TAP_LIST = 'TAP код';
export const DEF_PARAM_RTPL_NAME = 'НАЗВАНИЕ СПЕЦИАЛЬНОГО ТП';

export const DB_UNDEF = "undefine";
export const DB_NAME_RSS = "rss";
export const DB_NAME_RSSREP = "rssrep";
export const DB_NAME_RSSTEST = "rsstest";
export const DB_NAME_RSSTEST2 = "rsstest2";